### ISSUE TITLE
Node compatabillity

### ISSUE THREAD

**Issue by benrudolph** [HXLStandard/libhxl-js#1]
Hi David,

This is awesome; I'd love this for JS. I was thinking it might be worthwhile to make it compatible for node and not just the browser as most file reading will be done on server. Also in terms of design, I'd suggest something like a callback function when the file has been read (ex: https://github.com/wdavidw/node-csv). Node is single threaded so it depends on making all the long running tasks (like file reading) as asynchronous tasks which can be completed without blocking the main thread. I can help out with PR if that'd be useful. I think we should adhere to the standard specified in CommonJS (http://en.wikipedia.org/wiki/CommonJS). Underscore and D3 are also good examples of JS libraries that are compatible on the server and the browser

**Comment by davidmegginson** [comment]
The hxl.load method already uses a callback. The hxl.wrap method doesn't, but since it wraps pre-parsed data, it shouldn't cause a synchronous delay.

Added #16 to review the compatibility guidelines later.
