### ISSUE TITLE
Export data array

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-js#13]
Allow exporting a complete data array, without or without headers. Requested by @SimonbJohnson

**Comment by SimonbJohnson** [comment]
I've using lib-hxl.js in an application again and reconstructing the dataset is hard work having to iterate over the columns and then the rows.

**Comment by davidmegginson** [comment]
Added a method hxl.Source.exportArray(skipHeaders) to export the entire dataset. Essentially concats dataset.headers, dataset.displayTags, and dataset.rawData
