### ISSUE TITLE
Make filters simpler

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-js#2]
Fix filters to allow a single string spec, and to parse filter expressions for select from strings.

**Comment by davidmegginson** [comment]
The idea is to support something like this:

    dataset.withRows('#sector=WASH').each(...);

**Comment by davidmegginson** [comment]
Done. Users can now have expressions like the above.

**Comment by SimonbJohnson** [comment]
How do we pass multiple values through? I tried passing a list and it only used the first value

Filter:  ["#channel=E-cash"]
Output length: [Array(77)]
Filter: ["#sector=Immediate/Basic Needs", "#channel=E-cash"]
Output length: [Array(87)]

Do we chain the withRows operation twice?

**Comment by davidmegginson** [comment]
That should work. I'll take a look at the code.

**Comment by SimonbJohnson** [comment]
Closing.  I've just realised it is an OR operator rather than an AND is working as expected.
